"""Type stubs for tripy._core (C extension)."""
from __future__ import annotations

from typing import Any

class TriPyError(Exception): ...

__version__: str

def init() -> None: ...
def version() -> str: ...
def features() -> dict[str, bool]: ...
def active_variant(name: str) -> str: ...
def braincore(
    neurons: int = ..., iterations: int = ..., threshold: int = ...
) -> dict[str, Any]: ...
def harding_gate(count: int = ..., iterations: int = ...) -> dict[str, Any]: ...
def lattice_flip(bits: int = ..., iterations: int = ...) -> dict[str, Any]: ...
def run_tri(path: str) -> int: ...
